version: '3'
services:
  logs-to-discord:
    #image: ghcr.io/LostOnTheLine/logs-to-discord:latest
    image: lostontheline/logs-to-discord:latest
    container_name: logs-to-discord
    user: 1000:1000
    environment:
      PUID: 1000 #optional
      PGID: 1000 #optional
      LOG_FILE: /var/log/sample.log # Comma separated list if multiple files "/var/log/sample.log,/var/log/sample log file.txt,/var/log/my container/logfile.log"
      DISCORD_WEBHOOK: "https://discord.com/api/webhooks/your-webhook-url"
      #FILTER_BY_WORD: "error"
    volumes:
      - /docker/log/var/log:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    #security_opt:
    #  - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.scope=private"
